version: "3"
services:

    gaelo2:
        image: salimkanoun/gaelo:v2-dev
        container_name: gaelo2
        restart: unless-stopped
        volumes: ["gaelo_data:/var/www/html:Z"]
        environment:
                APP_NAME: GaelO
                APP_ENV: local
                APP_URL: https://0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud/
                DB_CONNECTION: mysql
                DB_HOST: gaelo_mysql
                DB_PORT: 3306
                DB_DATABASE: gaelo
                DB_USERNAME: gaelo
                DB_PASSWORD: gaelo
                MAIL_MAILER: smtp
                MAIL_HOST: smtp.sendgrid.net
                MAIL_PORT: 465
                MAIL_USERNAME: apikey
                MAIL_PASSWORD: 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
                MAIL_ENCRYPTION: ssl
                MAIL_FROM_ADDRESS: salim.kanoun@gmail.org
                QUEUE_CONNECTION: database
                GAELO_PATIENT_CODE_LENGTH: 14
                ORTHANC_TEMPORARY_ADDRESS: 'http://'
                ORTHANC_TEMPORARY_PORT: 8042
                ORTHANC_TEMPORARY_LOGIN: 'login'
                ORTHANC_TEMPORARY_PASSWORD: 'password'
                ORTHANC_STORAGE_ADDRESS: 'http://'
                ORTHANC_STORAGE_PORT: 8042
                ORTHANC_STORAGE_LOGIN: 'login'
                ORTHANC_STORAGE_PASSWORD: 'password'
        labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.blog.rule=Host(`0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud`)"
        - "traefik.http.routers.blog.entrypoints=websecure"
        
    php-queue:
        restart: always
        image: php:7.2-fpm
        command: php artisan queue:work
        volumes: 
            - gaelo_data:/var/www/html

    gaelo_mysql:
        image: mysql:5.7
        container_name: gaelo_mysql
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --log-bin-trust-function-creators=1]
        volumes: ["gaelo_mysql:/var/lib/mysql:Z"]
        environment:
                MYSQL_ENABLED: "true" 
                MYSQL_PASSWORD: gaelo
                MYSQL_USER: gaelo
                MYSQL_DATABASE: gaelo
                MYSQL_ROOT_PASSWORD: gaelo
                MYSQL_ROOT_HOST: "%"
        restart: unless-stopped
        
    reverse-proxy:
        image: traefik:v2.2
        container_name: traefik
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik.toml:/etc/traefik/traefik.toml
          - ./acme.json:/acme.json
        restart: always

volumes:
    gaelo_mysql:
    gaelo_data:
